import type { Metadata } from "next";


import { ClerkProvider, SignedIn, SignIn, UserButton } from "@clerk/nextjs";
import Navbar from "../components/nav";


const fontSans = {
  className: 'font-sans',
  variable: '--font-sans'
};

const fontMono = {
  className: 'font-mono',
  variable: '--font-mono'
};


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
  <html lang="en" data-theme="dark">
    <body className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}>
       <header className="fixed z-10 w-full ">
        <Navbar />
        </header>

            <div className="pt-24 bg-black">{children}</div>
    </body>
  </html>
</ClerkProvider>
  );
}
