import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Themeprovide from "./Themeprovider";

const fontSans = { className: "font-sans", variable: "--font-sans" };
const fontMono = { className: "font-mono", variable: "--font-mono" };

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="dark">
        <body className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}>
          <Themeprovide>{children}</Themeprovide>
        </body>
      </html>
    </ClerkProvider>
  );
}
