import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { ClerkProvider, SignedIn, SignIn, UserButton } from "@clerk/nextjs";
import Navbar from "../components/nav";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
  <html lang="en" data-theme="dark">
    <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
       <header className="fixed z-10 w-full ">
        <Navbar />
        </header>

            <div className="pt-24 bg-black">{children}</div>
    </body>
  </html>
</ClerkProvider>
  );
}
