import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

// USE THIS INSTEAD:
const fontSans = {
  className: 'font-sans', // Will use default system sans font
  variable: '--font-sans'
};

const fontMono = {
  className: 'font-mono', // Will use default system mono font
  variable: '--font-mono'
};

export const metadata: Metadata = {
  title: "Clipora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <ClerkProvider>
  <html lang="en" data-theme="dark">
    <body className={`${fontSans.variable} ${fontMono.variable} font-sans antialiased`}>
     

      {children}
    </body>
  </html>
</ClerkProvider>
  );
}
